apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_URI: bW9uZ29kYitzcnY6Ly9kYl9hZG1pbjpRd2VydHkxMjM0NUBjbHVzdGVyMC5qMDE5a3I0Lm1vbmdvZGIubmV0L2F3cy1tb25nby1kYj9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk=
